import { LevelRecipe } from '../Types/Types';
import { Utils } from '../Utils/Utils';

export const levels: LevelRecipe[] = [
  {
    staticObjectsRecipe: [
      Utils.makeStaticObjectRecipe('Brick', 20, 160, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Concrete', 20, 172, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 44, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 100, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 124, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 44, 208, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 44, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 244, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 44, 268, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 68, 160, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 100, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 160, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 124, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 92, 208, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 92, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 244, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 92, 268, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 52, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 140, 136, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 184, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 140, 196, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 140, 244, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Concrete', 164, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 164, 196, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 52, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 188, 136, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 184, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 188, 196, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 188, 244, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 236, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 100, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 160, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 124, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 236, 208, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 236, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 244, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 236, 268, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 256, 160, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 28, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 52, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 76, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 100, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 124, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 284, 208, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Brick', 284, 220, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 244, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 284, 268, 'Full'),
      Utils.makeStaticObjectRecipe('Brick', 308, 160, 'Horizontally'),
      Utils.makeStaticObjectRecipe('Concrete', 308, 172, 'Horizontally'),
      // Eagle Borders
      Utils.makeStaticObjectRecipe('Brick', 152, 292, 'Vertically', true),
      Utils.makeStaticObjectRecipe('Brick', 188, 292, 'Vertically', true),
      Utils.makeStaticObjectRecipe('Brick', 152, 280, 'Horizontally', true),
      Utils.makeStaticObjectRecipe('Brick', 176, 280, 'Horizontally', true),
    ],
    eagle: { xPos: 164, yPos: 292, size: 24 },
    enemyTanksList: ['Small', 'Small', 'Small'],
  },
];

